### ISSUE TITLE
build fails with stm32h7xx_hal

### ISSUE THREAD

**Issue by Flydroid** [atlas-aero/rt-LTC681X#6]
Hi @marius-meissner , 

I was happy to find that there is already a create implementing the LTC681x family. 
I'm working on a BMS based on the Portenta H7 development board 
and cell sensor board with two LTC6812 ICs. 

I have a working simple test code with spi in this commit: [1e2885d](https://github.com/Flydroid/rust-bms-testing/tree/1e2885d6b5d2cc4e77398e00b24a2ea0382bf050)

When I add the LTC681x create like this commit [b954de7](https://github.com/Flydroid/rust-bms-testing) the build fails with the message: 

```
error: no global memory allocator found but one is required; link to std or add `#[global_allocator]` to 
a static item that implements the GlobalAlloc trait
```

This shouldn't happen as the LTC681x crate is not using any alloc(), right?
I tried to check the heapless create, but except in its tests it also not using the std allocator. 
Then maybe an interaction with the STM32H7xx_hal create?

Any hints or suggestions on how to fix this issue would be very appreciated!

**Comment by Flydroid** [comment]
I managed to get unstuck, by removing `extern crate alloc` from the [lib.rs](https://github.com/atlas-aero/rt-LTC681X/blob/583a93028893f218b8abd8c828e61c18e61a1092/src/lib.rs#L47) source.

After that of course the tests don't compile anymore. 
In my project I must be missing something that suppresses that the test code gets compiled

**Comment by marius-meissner** [comment]
@Flydroid Thanks a lot for brining this up.
Shouldn't be a big deal for fixing this.
Could you please check if #7 viable solution?

**Comment by Flydroid** [comment]
@marius-meissner  Thanks for the quick fix! 
Yes it solves the build issue!
